#ifndef MAIN_H
#define MAIN_H

#include <Arduino.h>

#include "hardware/dma.h"
#include "hardware/pio.h"

#include "i8008.pio.h" // pin map + PIO programs, generated by pre_build.py
#include "i8008_decode.h"

#define CLK_DIV 66 // 133 MHz / 66 / 4 PIO steps = 504 kHz two-phase clock
// INT pulse length in clock periods. It must still be high when the chip
// enters T1I: with 2 periods, a halted chip sometimes woke, did a plain
// fetch and halted again; 3 still failed about 1 start in 20, 4 never has.
#define INT_PULSE_PERIODS 4

#define RAM_SIZE 16384 // the full 14-bit 8008 address space
#define RAM_MASK (RAM_SIZE - 1)

#define RING_WORDS 1024 // capture ring buffer, power of two
#define RING_BITS 12    // log2(RING_WORDS * 4) bytes, DMA write-address wrap

#define INT_JAM_INSTRUCTION 0x05 // RST 0, jammed during interrupt acknowledge cycles

// Raw 3-bit state codes as captured (S2 wired to the lowest gpio, hence the order).
enum {
	ST_WAIT = 0,
	ST_T2 = 1,
	ST_T1 = 2,
	ST_T1I = 3,
	ST_T3 = 4,
	ST_T5 = 5,
	ST_STOPPED = 6,
	ST_T4 = 7,
};

// D7:D6 cycle-control code, valid from T2 of each machine cycle.
enum {
	CYC_PCI = 0, // 00: instruction fetch
	CYC_PCC = 1, // 01: I/O command
	CYC_PCR = 2, // 10: memory data read (data and additional instruction bytes)
	CYC_PCW = 3, // 11: memory data write
};

#define EV_SERVED 0x01 // Pico queued this byte for the bus (set on the T2 event)
#define EV_WRITE 0x02  // memory write committed (set on the T3 event)
#define EV_INTACK 0x04 // cycle started with T1I (interrupt acknowledge)
#define EV_JAM 0x08    // served byte came from the jam sequence, not RAM
#define EV_OUT 0x10    // OUT committed to an output port (set on the T2 event)

typedef struct __attribute__((aligned(4))) {
	uint16_t raw;   // 14-bit capture: [2:0] S2..S0, [10:3] D0..D7, [11] BUS_WRITE, [12] READY, [13] INT
	uint16_t addr;  // address as latched so far
	uint8_t state;  // ST_*
	uint8_t cycle;  // CYC_*
	uint8_t served; // byte the Pico serves (valid with EV_SERVED)
	uint8_t flags;  // EV_*
} event_t;

// Lock-free SPSC event ring, core1 -> core0. Kept out of the pico-sdk queue
// on purpose: its code lives in flash, and an XIP stall on core 1 between a
// captured T2 and the serve push is enough to miss the T3 window.
#define EVQ_SIZE 1024 // power of two
extern event_t evq_buf[EVQ_SIZE];
extern volatile uint32_t evq_head, evq_tail; // head: core1 writes, tail: core0 reads

extern uint8_t i8008_ram[RAM_SIZE];

// I/O ports. INP 0-7 reads io_in[], OUT 8-31 lands in io_out[] (indexed by
// port number, so io_out[0..7] stay unused). A PCC cycle carries the
// accumulator at T1 and the instruction byte at T2, whose bits 5..1 are the
// port: 01 RRM MM1.
#define IO_IN_PORTS 8
#define IO_PORTS 32
#define IO_PORT(t2_byte) (((t2_byte) >> 1) & 0x1F)
extern volatile uint8_t io_in[IO_IN_PORTS];        // core 0 writes, core 1 serves
extern volatile uint8_t io_out[IO_PORTS];          // core 1 writes
extern volatile uint32_t io_out_count[IO_PORTS];   // core 1 writes

// Chip test support. Every OUT is also appended to io_log (port << 8 |
// value), an SPSC ring core 1 -> core 0 that the chip test drains. Core 1
// measures each instruction's length in T-states (PCI T2 to the next PCI
// T2, counted in capture samples, two per state) and keeps the shortest and
// longest seen per opcode; conditional instructions show both outcomes.
#define IO_LOG_SIZE 4096 // power of two
extern uint16_t io_log[IO_LOG_SIZE];
extern volatile uint32_t io_log_head, io_log_tail; // head: core1 writes, tail: core0
extern volatile bool trace_enabled;                // false: core 1 queues no trace events
extern volatile uint32_t pci_count;                // instruction fetches served
extern volatile uint8_t op_states_min[256], op_states_max[256];
extern volatile bool op_timing_reset; // core 0 sets after clearing the tables

void arm_jam(const uint8_t *seq, uint8_t len);
void int_pulse();
void set_clock_div(uint div);
void chip_test(bool full); // chip_test.cpp
extern volatile uint32_t evq_dropped;

// Jam sequence: instead of RAM, serve these bytes starting at the next
// instruction fetch (PCI), continuing over the following PCR cycles.
// {0x05} = RST 0 (boot); {0x44, lo, hi} = JMP addr (the 'j' command).
// Writer (core 0) must fill jam_seq and jam_pos first, jam_len last.
extern volatile uint8_t jam_seq[3];
extern volatile uint8_t jam_len, jam_pos;
extern volatile bool hw_ready;
extern uint32_t capture_ring[RING_WORDS];
extern int dma_ch;
extern uint sm_clk, sm_step, sm_int, sm_capture, sm_bus_write;
extern uint bus_write_offset;

void i8008_ram_load();
void bus_write_reset(); // drain + restart the bus_write SM, bus released

#endif
