#ifndef MAIN_H
#define MAIN_H

#include <Arduino.h>

#include "hardware/dma.h"
#include "hardware/pio.h"
#include "pico/util/queue.h"

#include "i8008.pio.h" // pin map + PIO programs, generated by pre_build.py
#include "i8008_decode.h"

#define CLK_DIV 66                   // 125 MHz / 66 / 4 PIO steps = 473 kHz two-phase clock
#define INT_PULSE_CYCLES (2 * 4 * CLK_DIV) // hold INT for two full clock periods

#define RAM_SIZE 16384 // the full 14-bit 8008 address space
#define RAM_MASK (RAM_SIZE - 1)

#define RING_WORDS 1024 // capture ring buffer, power of two
#define RING_BITS 12    // log2(RING_WORDS * 4) bytes, DMA write-address wrap

#define INT_JAM_INSTRUCTION 0x05 // RST 0, jammed during interrupt acknowledge cycles

// Raw 3-bit state codes as captured (S2 wired to the lowest gpio, hence the order).
enum {
	ST_WAIT = 0,
	ST_T2 = 1,
	ST_T1 = 2,
	ST_T1I = 3,
	ST_T3 = 4,
	ST_T5 = 5,
	ST_STOPPED = 6,
	ST_T4 = 7,
};

// D7:D6 cycle-control code, valid from T2 of each machine cycle.
enum {
	CYC_PCI = 0, // instruction fetch
	CYC_PCR = 1, // memory data read
	CYC_PCC = 2, // I/O command
	CYC_PCW = 3, // memory data write
};

#define EV_SERVED 0x01 // Pico queued this byte for the bus (set on the T2 event)
#define EV_WRITE 0x02  // memory write committed (set on the T3 event)
#define EV_INTACK 0x04 // cycle started with T1I (interrupt acknowledge)

typedef struct {
	uint16_t raw;   // 14-bit capture: [2:0] S2..S0, [10:3] D0..D7, [11] BUS_WRITE, [12] READY, [13] INT
	uint16_t addr;  // address as latched so far
	uint8_t state;  // ST_*
	uint8_t cycle;  // CYC_*
	uint8_t served; // byte the Pico serves (valid with EV_SERVED)
	uint8_t flags;  // EV_*
} event_t;

extern uint8_t i8008_ram[RAM_SIZE];
extern queue_t event_queue;
extern volatile uint32_t evq_dropped;
extern volatile bool hw_ready;
extern uint32_t capture_ring[RING_WORDS];
extern int dma_ch;
extern uint sm_clk, sm_step, sm_int, sm_capture, sm_bus_write;

void i8008_ram_load();

#endif
